# Usa una imagen base oficial de Node.js
FROM node:18

# Establece el directorio de trabajo en el contenedor
WORKDIR /backend

# Copia el archivo package.json y package-lock.json al directorio de trabajo
COPY backend/package*.json ./

# Instala las dependencias del proyecto
RUN npm install

# Instala nodemon, ts-node y typescript globalmente para hot reload
RUN npm install -g nodemon ts-node typescript

# Copia todo el código de la aplicación al directorio de trabajo
COPY backend .

# Expone el puerto en el que Nest.js se ejecutará
EXPOSE 3000

# Comando para iniciar la aplicación con hot reload
CMD ["nodemon", "--watch", "src", "--exec", "ts-node", "src/main.ts"]
